version: "3"
services:
  redis:
    image: redislabs/rejson:latest
    container_name: redisjson
    expose:
      - 6379

  server:
    build: .
    container_name: story_server
    ports:
      - 8085:8085
    depends_on:
      - redis
